### ISSUE TITLE
OreDicctionary Registration Warning

### ISSUE THREAD

**Issue by Handeril** [Ender-Development/Earthworks-Extended-Life#1]
Since this is forked from FreneticScribbler's version of Earthworks, I would trust that a number of bugs from the original Earthworks were fixed.

This small issue from the original mod was submitted _after_ the fork was made, however, and I'm wondering if you could spare a moment to fix it.

This is the issue: https://github.com/Alsender/Earthworks/issues/43

This is the erroring file.
https://github.com/Alsender/Earthworks/blob/1.12/src/main/java/alsender/earthworks/main/registry/BlockRegistry.java
The error occurs at line 239, as stated in the error, where an attempt is made to register something under "plankWood" in OreDictionary.

Thank you for your time, nonetheless, for looking into this.

**Comment by Klebestreifen** [comment]
I suspect it is because the OreDictionary may be registered in the wrong event. I'll try to fix that in a timely manner.

When I looked at the code I felt sick. It should be refactored completely.
