### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by jimmyG1** [Ender-Development/Earthworks-Extended-Life#2]
will this be updated to 1.18.2 for forge

**Comment by Klebestreifen** [comment]
Currently, this is not planned. The mod is only maintained by us but not further developed.

**Comment by MasterEnderman** [comment]
There is a version for 1.16, but it doesn't look like it'll will be updated any time soon.

Reference: https://legacy.curseforge.com/minecraft/mc-mods/earth-reworked

Like stated before, we're only focusing version 1.12.2 for now. Everything else only time will tell.
